language: python
python:
  - "3.6"
cache: pip
# install:
#   - pip install -r requirements.txt
script:
  - python tests.py
deploy:
  provider: lambda
  function_name: "ucsb-sa-ssis-statuspage-webhook-sample"
  region: "us-west-2"
  role: "arn:aws:iam::035849207430:role/service-role/ucsb-sa-ssis-statuspage-webhook-sample-role-bfgcv0r2"
  runtime: "python3.7"
  handler_name: "handler"
